### PR TITLE
Update the README and version

### PR DESCRIPTION
**Pull request by dayjournal**
_Issue #, if available:_
#28

_Description of changes:_
- Update the README 
Added to the documentation of placeToFeatureCollection

- version to 1.0.3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dayjournal** [comment]
Hi, @eashuang, @juaneslucero
Changed documentation and npm version of placeToFeatureCollection. 
Please check! 🙇‍♂

**Review by eashuang — APPROVED** [review]
You don't have to make the version change as we are going to include the version change during release. But thanks!

**Review by wq-van — APPROVED** [review]

**Comment by dayjournal** [comment]
Hi, @eashuang 
I want to write an article using this library, when will it be reflected in npm?

**Review by juaneslucero — APPROVED** [review]

**Comment by eashuang** [comment]
Thanks for the contribution @dayjournal. We have just released the 1.0.3 version to npm.

**Pull request merged**
